/**
 * GENERATED by scripts/process-v2-features.mjs from ALLSCOPE_ENHANCED_4K_V2.
 * Feature photography for the homepage, capabilities, about, safety and
 * tender pages. Do not edit by hand; edit the slot table and re-run.
 */

export interface FeaturePhoto {
  src: string;
  width: number;
  height: number;
  alt: string;
}

export const featurePhotos = {
  "home-band": {
    "src": "/media/features/home-band.webp",
    "width": 1800,
    "height": 2400,
    "alt": "Allscope boom pump raised between two Allscope branded trucks beside a freshly finished slab"
  },
  "home-slab": {
    "src": "/media/features/home-slab.webp",
    "width": 2400,
    "height": 979,
    "alt": "Freshly finished commercial ground slab with column starter cages and a trowel operator working the far edge"
  },
  "cap-placement": {
    "src": "/media/features/cap-placement.webp",
    "width": 2400,
    "height": 1800,
    "alt": "Wide suspended slab pour with the boom pump overhead and a power trowel operator in the foreground"
  },
  "cap-finishing": {
    "src": "/media/features/cap-finishing.webp",
    "width": 1800,
    "height": 2400,
    "alt": "Crew screeding and trowelling a broad freshly poured basement ramp slab"
  },
  "cap-pumping": {
    "src": "/media/features/cap-pumping.webp",
    "width": 1800,
    "height": 2400,
    "alt": "Two agitator trucks feeding an Allscope branded boom pump at sunset while the crew places concrete"
  },
  "cap-prepour": {
    "src": "/media/features/cap-prepour.webp",
    "width": 1800,
    "height": 2400,
    "alt": "Beam cages and top reinforcement fixed over metal deck formwork on a large suspended slab"
  },
  "cap-planning": {
    "src": "/media/features/cap-planning.webp",
    "width": 1800,
    "height": 2400,
    "alt": "Tower crane rising from a formed lift core above a basement raft prepared with membrane and starter cages"
  },
  "cap-band": {
    "src": "/media/features/cap-band.webp",
    "width": 1448,
    "height": 1086,
    "alt": "Aerial view of a large basement raft pour with two concrete pump booms, queued agitator trucks and crews spreading concrete"
  },
  "about-pour": {
    "src": "/media/features/about-pour.webp",
    "width": 1800,
    "height": 2400,
    "alt": "Concreting crew working the wet edge of a large commercial slab pour over mesh reinforcement"
  },
  "about-completed": {
    "src": "/media/features/about-completed.webp",
    "width": 2057,
    "height": 2400,
    "alt": "Curved freshly finished concrete path with a broom finish running through a landscaped garden"
  },
  "safety-crew": {
    "src": "/media/features/safety-crew.webp",
    "width": 1800,
    "height": 2400,
    "alt": "Harnessed concreters screeding wet concrete along a narrow elevated walkway between timber edge forms"
  },
  "safety-trowel": {
    "src": "/media/features/safety-trowel.webp",
    "width": 2070,
    "height": 2400,
    "alt": "Two ride-on trowel operators finishing a large fresh commercial slab around column starter cages"
  },
  "safety-slab": {
    "src": "/media/features/safety-slab.webp",
    "width": 2400,
    "height": 1331,
    "alt": "Ride-on power trowel on a freshly finished concrete slab with starter bars along the perimeter wall"
  },
  "tenders-deck": {
    "src": "/media/features/tenders-deck.webp",
    "width": 1800,
    "height": 2400,
    "alt": "Reinforced deck laid with mesh ready for concrete, with the pour underway in the distance"
  }
} as const satisfies Record<string, FeaturePhoto>;

export type FeatureSlot = keyof typeof featurePhotos;
