/**
 * GENERATED by scripts/process-gallery.mjs from the authored owner-photo
 * selections (folder 03, 98-GENERAL and 99-UNCONFIRMED batches). Do not edit
 * by hand — adjust the selections in the script and re-run it. None of these
 * photographs is attributed to a named project by design.
 */

export interface GalleryPhoto {
  src: string;
  width: number;
  height: number;
  orientation: "landscape" | "portrait" | "square";
  alt: string;
}

export const galleryPhotos: GalleryPhoto[] = [
  {
    "src": "/media/gallery/GAL-149.webp",
    "width": 2000,
    "height": 2000,
    "orientation": "square",
    "alt": "A wide basement raft pour in progress, finishers screeding behind the pump hose with power trowels standing by."
  },
  {
    "src": "/media/gallery/GAL-005.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "In-situ concrete planter and retaining walls with tanking and reinforcement, finished apartment buildings behind."
  },
  {
    "src": "/media/gallery/GAL-197.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "A finished charcoal driveway with a contrast border band and trench grate."
  },
  {
    "src": "/media/gallery/GAL-146.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "A boom pump placing a suspended slab in a basement, the crew screeding the fresh concrete below."
  },
  {
    "src": "/media/gallery/GAL-062.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "Fresh kerb and gutter laid along a new street at dusk, finishers working further up the run."
  },
  {
    "src": "/media/gallery/GAL-166.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "A freshly floated basement slab with a drain grate and capped starter bars."
  },
  {
    "src": "/media/gallery/GAL-031.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "Footing cages placed below an anchored shoring wall in a bulk excavation."
  },
  {
    "src": "/media/gallery/GAL-169.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "An operator power trowelling a fresh slab, a boom pump and scaffolded building behind."
  },
  {
    "src": "/media/gallery/GAL-177.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "Steel fixers tying deck reinforcement between tilt panels."
  },
  {
    "src": "/media/gallery/GAL-030.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "New concrete steps and ramp at dusk, the fresh finish still holding its sheen."
  },
  {
    "src": "/media/gallery/GAL-067.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "A basement floor sheeted in waterproofing membrane ahead of the raft pour, seen from above."
  },
  {
    "src": "/media/gallery/GAL-162.webp",
    "width": 2000,
    "height": 1500,
    "orientation": "landscape",
    "alt": "Formed footing boxes with mesh in place beside a tilt-panel warehouse."
  },
  {
    "src": "/media/gallery/GAL-213.webp",
    "width": 2000,
    "height": 2319,
    "orientation": "portrait",
    "alt": "A fresh slab stretching away between column starter cages and blockwork walls."
  },
  {
    "src": "/media/gallery/GAL-152.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "Mesh, membrane and starter bars checked on the morning of a raft pour."
  },
  {
    "src": "/media/gallery/GAL-155.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "A freshly floated slab in the foreground with the finishing crew working beyond."
  },
  {
    "src": "/media/gallery/GAL-209.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "Mesh and membrane laid for the next pour, the finished slab and pump truck beyond."
  },
  {
    "src": "/media/gallery/GAL-045.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "Curved footpath formwork set out along a building frontage at dusk."
  },
  {
    "src": "/media/gallery/GAL-056.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "A pump line dropped between completed apartment buildings to reach a courtyard pour."
  },
  {
    "src": "/media/gallery/GAL-172.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "A freshly finished slab beside a bulk excavation, seen from above."
  },
  {
    "src": "/media/gallery/GAL-198.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "A finished dark driveway apron with a curved formed edge."
  },
  {
    "src": "/media/gallery/GAL-018.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "Fresh footpath panels poured beside an apartment building."
  },
  {
    "src": "/media/gallery/GAL-205.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "Allscope crew placing concrete at a slab edge under a storm sky."
  },
  {
    "src": "/media/gallery/GAL-208.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "A fresh slab with column starter cages rising from it, blockwork walls behind."
  },
  {
    "src": "/media/gallery/GAL-163.webp",
    "width": 2000,
    "height": 1500,
    "orientation": "landscape",
    "alt": "Formwork and mesh set out for footings alongside tilt panels."
  },
  {
    "src": "/media/gallery/GAL-033.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "Footing and lift-pit pours under way in a bulk excavation, the pump line run down from street level."
  },
  {
    "src": "/media/gallery/GAL-040.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "Mesh and formwork ready for a courtyard slab between terrace walls."
  },
  {
    "src": "/media/gallery/GAL-043.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "A shored basement excavation with capping beams poured and starter bars ready for footings."
  },
  {
    "src": "/media/gallery/GAL-049.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "An Allscope finisher on a fresh textured walkway between apartment buildings."
  },
  {
    "src": "/media/gallery/GAL-050.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "A finished footpath running along a terrace frontage with new street trees."
  },
  {
    "src": "/media/gallery/GAL-052.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "Walkway deck reinforcement fixed over void formers between buildings."
  },
  {
    "src": "/media/gallery/GAL-053.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "The crew finishing a fresh laneway slab between apartment buildings."
  },
  {
    "src": "/media/gallery/GAL-061.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "Reinforcement set out for a curved driveway and paths between buildings."
  },
  {
    "src": "/media/gallery/GAL-068.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "A footing pour in progress at the base of a deep shored excavation."
  },
  {
    "src": "/media/gallery/GAL-069.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "The pump boom reaching over a shored excavation during an early works pour."
  },
  {
    "src": "/media/gallery/GAL-147.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "A fresh concrete path running along a gabion stone wall."
  },
  {
    "src": "/media/gallery/GAL-148.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "A residential driveway pour in progress, the agitator truck backed up to the forms."
  },
  {
    "src": "/media/gallery/GAL-156.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "Deck mesh and membrane down, the pump set up beside the warehouse for pour day."
  },
  {
    "src": "/media/gallery/GAL-167.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "Swirl finish on a fresh backyard slab."
  },
  {
    "src": "/media/gallery/GAL-212.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "alt": "Two ride-on trowels working a fresh slab between column starter cages."
  },
  {
    "src": "/media/gallery/GAL-215.webp",
    "width": 2000,
    "height": 816,
    "orientation": "landscape",
    "alt": "A freshly poured and finished deck, starter bars ready for the next lift."
  }
];
