/**
 * GENERATED by scripts/process-enh4k-gallery.mjs from the curated selection in
 * scripts/gallery-selection.json (ALLSCOPE_ENHANCED_4K collection, all 222
 * photographs reviewed; this file holds the ordered gallery picks only).
 * Do not edit by hand; edit the selection and re-run the script.
 */

export interface GalleryPhoto {
  thumb: string;
  full: string;
  width: number;
  height: number;
  orientation: "landscape" | "portrait";
  alt: string;
  caption?: string;
  role: "featured" | "support" | "row";
}

export const galleryPhotos: GalleryPhoto[] = [
  {
    "thumb": "/media/gallery/thumb/img-1068.webp",
    "full": "/media/gallery/full/img-1068.webp",
    "width": 1000,
    "height": 1000,
    "orientation": "landscape",
    "alt": "Golden-hour view across a large slab deck laid with reinforcement mesh and column starter cages, with a concrete pump boom arcing over blockwork walls ready for the pour.",
    "caption": "Reinforcement and formwork",
    "role": "featured"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-20-56-50-1-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-20-56-50-1-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Red concrete pump boom arcing over a freshly poured commercial floor slab with capped starter bars in the foreground and the placing crew working along the far edge.",
    "caption": "Concrete pumping operation",
    "role": "support"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-33-41-19-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-33-41-19-.webp",
    "width": 960,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Expansive post-tensioned deck reinforcement stretching to the horizon with beam formwork and crews working in the distance.",
    "caption": "Reinforcement and formwork",
    "role": "support"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-20-58-17-1-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-20-58-17-1-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Harnessed concreters screed wet concrete along a narrow elevated walkway between timber edge forms with the city skyline behind.",
    "caption": "Concrete placement and finishing",
    "role": "support"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-20-58-23.webp",
    "full": "/media/gallery/full/photo-2026-07-29-20-58-23.webp",
    "width": 1000,
    "height": 642,
    "orientation": "landscape",
    "alt": "Twilight view of a completed school courtyard with tiered concrete amphitheatre seating and checkerboard paving.",
    "caption": "Structural concrete works",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/img-1040.webp",
    "full": "/media/gallery/full/img-1040.webp",
    "width": 1000,
    "height": 750,
    "orientation": "landscape",
    "alt": "Aerial view of a large basement raft pour with two concrete pump booms, queued agitator trucks and crews spreading wet concrete across the reinforced deck.",
    "caption": "Commercial concrete construction",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-33-41-24-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-33-41-24-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Two agitator trucks feeding an Allscope branded boom pump at sunset while the crew places concrete on a formed structure against an orange sky.",
    "caption": "Concrete pumping operation",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-20-56-25-2-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-20-56-25-2-.webp",
    "width": 1000,
    "height": 750,
    "orientation": "landscape",
    "alt": "Wide suspended slab pour with the boom pump overhead, a power trowel operator in the foreground and finishers spread across the fresh deck.",
    "caption": "Commercial concrete construction",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-23-09-11-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-23-09-11-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Blue tower crane rising from a formed lift core above a basement raft prepared with black waterproofing membrane, top mesh and yellow-capped column starter cages.",
    "caption": "Commercial concrete construction",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-33-26.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-33-26.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Crew screeding and trowelling a broad freshly poured basement ramp slab with the pump truck working above.",
    "caption": "Concrete placement and finishing",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-23-09-23-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-23-09-23-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Concrete pump boom arcing across a deep blue sky beside a tower crane, its hose reaching down to a suspended formwork deck.",
    "caption": "Concrete pumping operation",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-20-56-54-2-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-20-56-54-2-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Beam cages and top reinforcement fixed over blue metal deck formwork on a large suspended slab, with a red pump boom overhead and a full crew across the deck.",
    "caption": "Reinforcement and formwork",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-23-09-41-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-23-09-41-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Concrete pump boom and hose feeding a crew pouring formed planter walls between finished apartment buildings under blue sky.",
    "caption": "Concrete pumping operation",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-20-58-11.webp",
    "full": "/media/gallery/full/photo-2026-07-29-20-58-11.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Elevated view of a long basement slab pour with a ride-on trowel and hand finishers working the fresh surface.",
    "caption": "Commercial concrete construction",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-33-40-9-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-33-40-9-.webp",
    "width": 896,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Overhead view of S-curved edge formwork with timber bracing around freshly placed concrete landscape terraces.",
    "caption": "Reinforcement and formwork",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-20-56-53.webp",
    "full": "/media/gallery/full/photo-2026-07-29-20-56-53.webp",
    "width": 1000,
    "height": 1000,
    "orientation": "landscape",
    "alt": "Large basement raft slab pour in progress with the finishing crew screeding and power trowelling fresh concrete between shotcrete walls, pump line entering from above.",
    "caption": "Commercial concrete construction",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-23-09-24-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-23-09-24-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Crews tying reinforcement in the foreground while a suspended slab formwork deck of yellow bearers spreads out beneath a pump boom and crane mast.",
    "caption": "Reinforcement and formwork",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-33-41-29-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-33-41-29-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Allscope boom pump stands raised between two Allscope branded trucks beside a freshly finished slab with reinforcement and formwork in the foreground.",
    "caption": "Concrete pumping operation",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-20-58-20.webp",
    "full": "/media/gallery/full/photo-2026-07-29-20-58-20.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "A concreting crew works the wet edge of a large commercial slab pour over mesh reinforcement beneath a dramatic storm sky.",
    "caption": "Concrete pumping operation",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-23-07-7-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-23-07-7-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Straight-on view of crisp off-form concrete planter and pool walls with waterproofed faces and reinforcement beyond, framed by apartment buildings with perforated screens.",
    "caption": "Reinforcement and formwork",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-20-56-53-1-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-20-56-53-1-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Elevated view into a deep basement excavation with a red pump boom and tower crane above, the suspended deck freshly poured and the crew placing concrete at the far edge.",
    "caption": "Concrete pumping operation",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-33-40-8-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-33-40-8-.webp",
    "width": 561,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Curved suspended deck with reinforcement and column starter bars over black formply, framed by scaffolding in golden hour light.",
    "caption": "Reinforcement and formwork",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-20-58-22-2-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-20-58-22-2-.webp",
    "width": 863,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Two ride-on trowel operators finish a large fresh commercial slab around column starter cages with a pump truck behind.",
    "caption": "Concrete placement and finishing",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-23-09-34-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-23-09-34-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Allscope-branded concreter inspecting a freshly finished walkway ramp framed by white perforated facade screens.",
    "caption": "Concrete placement and finishing",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-33-41-21-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-33-41-21-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Boom pump reaching over a shotcrete retaining wall into a basement raft pour with fresh concrete spreading and crews on the mesh.",
    "caption": "Concrete pumping operation",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/img-1033.webp",
    "full": "/media/gallery/full/img-1033.webp",
    "width": 1000,
    "height": 555,
    "orientation": "landscape",
    "alt": "A ride-on power trowel sits on a freshly finished concrete slab with starter bars projecting from the perimeter wall behind.",
    "caption": "Concrete pumping operation",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-23-09-43-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-23-09-43-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Close view of wet concrete being placed over reinforcement mesh and bar chairs against a screeded slab edge.",
    "caption": "Concrete placement and finishing",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-33-40-4-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-33-40-4-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Reinforcement mesh on bar chairs over black waterproofing membrane between precast panels, with blue puddle flanges and penetrations ready for a slab pour.",
    "caption": "Reinforcement and formwork",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-20-58-22.webp",
    "full": "/media/gallery/full/photo-2026-07-29-20-58-22.webp",
    "width": 1000,
    "height": 408,
    "orientation": "landscape",
    "alt": "Panoramic view of a freshly finished commercial ground slab with column cages, a trowel operator and a pump truck at the boundary.",
    "caption": "Commercial concrete construction",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-23-09-39-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-23-09-39-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Finishers kneeling to trowel a fresh driveway slab between completed apartment buildings with a pump line hanging overhead.",
    "caption": "Concrete placement and finishing",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-33-41-12-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-33-41-12-.webp",
    "width": 1000,
    "height": 750,
    "orientation": "landscape",
    "alt": "Elevated landscape view of deck formwork and reinforcement with crews at work, parkland and shade sails in the background.",
    "caption": "Commercial concrete construction",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-23-09-47-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-23-09-47-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Freshly poured kerb and gutter running up a new road with finishers working along it beside a completed footpath.",
    "caption": "Concrete placement and finishing",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-20-56-49.webp",
    "full": "/media/gallery/full/photo-2026-07-29-20-56-49.webp",
    "width": 857,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Freshly poured exposed aggregate driveway curving down a sloped residential block with edge formwork still in place and two workers in the background.",
    "caption": "Structural concrete works",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-33-41-14-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-33-41-14-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Elevated view over wall formwork and a reinforced deck with multiple crews at work beneath a Strictly Cranes tower crane jib.",
    "caption": "Commercial concrete construction",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-23-09-40-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-23-09-40-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Crew placing reinforcement mesh on bar chairs over a formed podium walkway slab between apartment blocks ready for pour.",
    "caption": "Reinforcement and formwork",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-23-09-9-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-23-09-9-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "View along a pump boom line into a basement excavation where crews pour reinforced pile caps below an apartment tower.",
    "caption": "Concrete pumping operation",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-20-56-56-2-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-20-56-56-2-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Reinforcement mesh over membrane on a warehouse ramp in the foreground with a freshly poured slab and concrete pump truck working beyond.",
    "caption": "Reinforcement and formwork",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-20-58-20-2-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-20-58-20-2-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Allscope concreters place and vibrate wet concrete across a reinforced suspended deck under a storm sky flanked by tower cranes.",
    "caption": "Concrete pumping operation",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-33-41-28-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-33-41-28-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Allscope concrete and pumping crane truck parked beside a freshly broom-finished slab with yellow edge forms in the foreground.",
    "caption": "Concrete pumping operation",
    "role": "row"
  },
  {
    "thumb": "/media/gallery/thumb/photo-2026-07-29-18-23-09-38-.webp",
    "full": "/media/gallery/full/photo-2026-07-29-18-23-09-38-.webp",
    "width": 750,
    "height": 1000,
    "orientation": "portrait",
    "alt": "Two concreters finishing a freshly poured stencilled walkway ramp between white perforated facade screens.",
    "caption": "Concrete placement and finishing",
    "role": "row"
  }
];
