/**
 * GENERATED by scripts/build-media-data.mjs from the supplied photo-library
 * manifests (04_MANIFESTS) plus the folder 03/04 4K photo packs (owner
 * photos and exact-project photography, integrated 20 Aug 2026). Do not edit
 * by hand — re-run the generator after a new library drop. Publish rules and
 * context-only constraints are encoded here from the registers; renders/CGI,
 * people-dominant and third-party-branded imagery are excluded at source.
 * Builder photo-use approval + project confirmation recorded 19 Aug 2026;
 * folder 03/04 photo permissions verified (user confirmation 20 Aug 2026).
 */

export type ProjectSector =
  | "industrial"
  | "multi-residential"
  | "mixed-use"
  | "commercial"
  | "hospitality"
  | "education"
  | "retail-fuel";

export type ProjectStatus =
  | "completed"
  | "under-construction"
  | "stage-2-under-construction";

export interface GalleryImage {
  assetId: string;
  src: string;
  width: number;
  height: number;
  orientation: "landscape" | "portrait" | "square";
  /** Register quality tier: A hero-capable … D detail/mobile only. */
  tier: "A" | "B" | "C" | "D";
  /** Architectural render — must carry an "Artist's impression" label.
   *  (No published image sets this since the 20 Aug 2026 image audit.) */
  render: boolean;
  /** Context-only: captions must not claim project proof or identify people. */
  contextOnly: boolean;
  caption: string;
}

export interface ProjectRecord {
  slug: string;
  order: number;
  code: string;
  name: string;
  location: string;
  sector: ProjectSector;
  /** Delivery team as recorded in the register (client / builder / architect). */
  team: string;
  legacyPage: string | null;
  status: ProjectStatus;
  statusNote: string | null;
  lead: {
    assetId: string;
    /** Overlay label for the lead (e.g. "Project context"); null for none. */
    label: string | null;
    src: string;
    width: number;
    height: number;
    preferredCrop: string;
  };
  gallery: GalleryImage[];
}

export interface CapabilityImage {
  assetId: string;
  src: string;
  width: number;
  height: number;
  orientation: "landscape" | "portrait" | "square";
  tier: "A" | "B" | "C" | "D";
  caption: string;
  purpose: string;
}

export const projectRecords: ProjectRecord[] = [
  {
    "slug": "kennards-macquarie-park",
    "order": 1,
    "code": "KMP",
    "name": "Kennards Self Storage",
    "location": "Macquarie Park",
    "sector": "industrial",
    "team": "Kennards Self Storage / Total Construction",
    "legacyPage": "https://allscopeconcrete.com.au/industrial-2/industrial-projects/",
    "status": "completed",
    "statusNote": null,
    "lead": {
      "assetId": "OJ4-KMP-03",
      "label": null,
      "src": "/media/leads/OJ4-KMP-03.webp",
      "width": 2400,
      "height": 1597,
      "preferredCrop": "16:9 desktop / 4:5 mobile; protect main structure and a quiet text zone"
    },
    "gallery": [
      {
        "assetId": "ASC-KMP-004",
        "src": "/media/projects/kennards-macquarie-park/ASC-KMP-004.webp",
        "width": 4256,
        "height": 2832,
        "orientation": "landscape",
        "tier": "A",
        "render": false,
        "contextOnly": false,
        "caption": "Low-angle orange-clad completed exterior."
      },
      {
        "assetId": "ASC-KMP-005",
        "src": "/media/projects/kennards-macquarie-park/ASC-KMP-005.webp",
        "width": 4256,
        "height": 2832,
        "orientation": "landscape",
        "tier": "A",
        "render": false,
        "contextOnly": false,
        "caption": "Side service-drive exterior."
      },
      {
        "assetId": "ASC-KMP-006",
        "src": "/media/projects/kennards-macquarie-park/ASC-KMP-006.webp",
        "width": 4256,
        "height": 2832,
        "orientation": "landscape",
        "tier": "A",
        "render": false,
        "contextOnly": false,
        "caption": "Three-quarter full completed exterior."
      },
      {
        "assetId": "ASC-KMP-007",
        "src": "/media/projects/kennards-macquarie-park/ASC-KMP-007.webp",
        "width": 4256,
        "height": 2832,
        "orientation": "landscape",
        "tier": "A",
        "render": false,
        "contextOnly": false,
        "caption": "Storage corridor and lift."
      },
      {
        "assetId": "ASC-KMP-008",
        "src": "/media/projects/kennards-macquarie-park/ASC-KMP-008.webp",
        "width": 4256,
        "height": 2832,
        "orientation": "landscape",
        "tier": "A",
        "render": false,
        "contextOnly": false,
        "caption": "Orange storage corridor."
      },
      {
        "assetId": "ASC-KMP-009",
        "src": "/media/projects/kennards-macquarie-park/ASC-KMP-009.webp",
        "width": 4256,
        "height": 2832,
        "orientation": "landscape",
        "tier": "A",
        "render": false,
        "contextOnly": false,
        "caption": "Empty storage unit with polished concrete slab."
      },
      {
        "assetId": "ASC-KMP-010",
        "src": "/media/projects/kennards-macquarie-park/ASC-KMP-010.webp",
        "width": 4256,
        "height": 2832,
        "orientation": "landscape",
        "tier": "A",
        "render": false,
        "contextOnly": false,
        "caption": "Lift and internal detail."
      },
      {
        "assetId": "ASC-KMP-001",
        "src": "/media/projects/kennards-macquarie-park/ASC-KMP-001.webp",
        "width": 1200,
        "height": 798,
        "orientation": "landscape",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Completed orange-clad storage exterior."
      },
      {
        "assetId": "ASC-KMP-002",
        "src": "/media/projects/kennards-macquarie-park/ASC-KMP-002.webp",
        "width": 1200,
        "height": 798,
        "orientation": "landscape",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Internal storage corridor and lift."
      },
      {
        "assetId": "ASC-KMP-003",
        "src": "/media/projects/kennards-macquarie-park/ASC-KMP-003.webp",
        "width": 1200,
        "height": 798,
        "orientation": "landscape",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Completed rear/service exterior."
      }
    ]
  },
  {
    "slug": "ed-square",
    "order": 2,
    "code": "EDS",
    "name": "Ed.Square — Arlington & Clifton",
    "location": "Edmondson Park",
    "sector": "multi-residential",
    "team": "Frasers Property / Binah / Plus Architecture",
    "legacyPage": "https://allscopeconcrete.com.au/ed-square/",
    "status": "completed",
    "statusNote": null,
    "lead": {
      "assetId": "ASC-EDS-003",
      "label": null,
      "src": "/media/leads/PROJECT-02-ED-SQUARE-01.webp",
      "width": 1742,
      "height": 1225,
      "preferredCrop": "16:9 desktop / 4:5 mobile; protect main structure and a quiet text zone"
    },
    "gallery": [
      {
        "assetId": "ASC-EDS-004",
        "src": "/media/projects/ed-square/ASC-EDS-004.webp",
        "width": 1899,
        "height": 1267,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Tower and retail precinct at night."
      },
      {
        "assetId": "ASC-EDS-011",
        "src": "/media/projects/ed-square/ASC-EDS-011.webp",
        "width": 1934,
        "height": 1290,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Rooftop garden and outlook."
      },
      {
        "assetId": "ASC-EDS-012",
        "src": "/media/projects/ed-square/ASC-EDS-012.webp",
        "width": 1916,
        "height": 1278,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Ground-level landscape and hospitality edge."
      },
      {
        "assetId": "ASC-EDS-005",
        "src": "/media/projects/ed-square/ASC-EDS-005.webp",
        "width": 1679,
        "height": 1355,
        "orientation": "landscape",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Tower and roundabout context."
      },
      {
        "assetId": "ASC-EDS-006",
        "src": "/media/projects/ed-square/ASC-EDS-006.webp",
        "width": 1579,
        "height": 1034,
        "orientation": "landscape",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Residential façade and podium landscaping."
      },
      {
        "assetId": "ASC-EDS-007",
        "src": "/media/projects/ed-square/ASC-EDS-007.webp",
        "width": 1836,
        "height": 1380,
        "orientation": "landscape",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Balcony and façade detail."
      },
      {
        "assetId": "ASC-EDS-008",
        "src": "/media/projects/ed-square/ASC-EDS-008.webp",
        "width": 1966,
        "height": 1311,
        "orientation": "landscape",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Completed apartment interior."
      },
      {
        "assetId": "ASC-EDS-009",
        "src": "/media/projects/ed-square/ASC-EDS-009.webp",
        "width": 1915,
        "height": 1278,
        "orientation": "landscape",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Rooftop terrace with tables."
      },
      {
        "assetId": "ASC-EDS-010",
        "src": "/media/projects/ed-square/ASC-EDS-010.webp",
        "width": 1913,
        "height": 1276,
        "orientation": "landscape",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Covered rooftop garden."
      },
      {
        "assetId": "ASC-EDS-013",
        "src": "/media/projects/ed-square/ASC-EDS-013.webp",
        "width": 1920,
        "height": 1281,
        "orientation": "landscape",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Low-angle tower façade."
      },
      {
        "assetId": "OJ4-EDS-01",
        "src": "/media/projects/ed-square/OJ4-EDS-01.webp",
        "width": 2000,
        "height": 1335,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Rooftop hardscape across the completed podium at Ed.Square."
      },
      {
        "assetId": "OJ4-EDS-02",
        "src": "/media/projects/ed-square/OJ4-EDS-02.webp",
        "width": 2000,
        "height": 1334,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Courtyard walkway, paving and planter edges at Ed.Square."
      }
    ]
  },
  {
    "slug": "babylon",
    "order": 3,
    "code": "BAB",
    "name": "Babylon",
    "location": "Rouse Hill",
    "sector": "multi-residential",
    "team": "Denvell / Binah / Rothelowman",
    "legacyPage": "https://allscopeconcrete.com.au/babylon/",
    "status": "completed",
    "statusNote": null,
    "lead": {
      "assetId": "OJ4-BAB-01",
      "label": null,
      "src": "/media/leads/OJ4-BAB-01.webp",
      "width": 2400,
      "height": 1601,
      "preferredCrop": "16:9 desktop / 4:5 mobile; protect main structure and a quiet text zone"
    },
    "gallery": [
      {
        "assetId": "OJ4-BAB-02",
        "src": "/media/projects/babylon/OJ4-BAB-02.webp",
        "width": 2000,
        "height": 1334,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Courtyard hardscape and planter faces in the completed courtyard."
      },
      {
        "assetId": "OJ4-BAB-03",
        "src": "/media/projects/babylon/OJ4-BAB-03.webp",
        "width": 2000,
        "height": 1334,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "The wider courtyard, its slab and planter edges at Babylon."
      }
    ]
  },
  {
    "slug": "auburn-square",
    "order": 4,
    "code": "AUB",
    "name": "Auburn Square — Stages 1 & 2",
    "location": "Auburn",
    "sector": "mixed-use",
    "team": "LFD / Binah / Rothelowman",
    "legacyPage": "https://allscopeconcrete.com.au/auburn-square/",
    "status": "stage-2-under-construction",
    "statusNote": "Stage 1 completed · Stage 2 under construction",
    "lead": {
      "assetId": "ASC-AUB-001",
      "label": null,
      "src": "/media/leads/PROJECT-04-AUBURN-SQUARE-01.webp",
      "width": 1300,
      "height": 867,
      "preferredCrop": "16:9 desktop / 4:5 mobile; protect main structure and a quiet text zone"
    },
    "gallery": [
      {
        "assetId": "ASC-AUB-003",
        "src": "/media/projects/auburn-square/ASC-AUB-003.webp",
        "width": 1200,
        "height": 1551,
        "orientation": "portrait",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Completed Auburn Square corner exterior at dusk."
      },
      {
        "assetId": "ASC-AUB-002",
        "src": "/media/projects/auburn-square/ASC-AUB-002.webp",
        "width": 1200,
        "height": 800,
        "orientation": "landscape",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Finished interior/lobby detail."
      },
      {
        "assetId": "OJ4-AUB-01",
        "src": "/media/projects/auburn-square/OJ4-AUB-01.webp",
        "width": 2000,
        "height": 1334,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Stage 1 courtyard hardscape at Auburn Square."
      }
    ]
  },
  {
    "slug": "sydney-international-airport",
    "order": 5,
    "code": "SYD",
    "name": "Sydney International Airport — T1 Departures Immigration Hall",
    "location": "Mascot",
    "sector": "commercial",
    "team": "Sydney Airport / Versatile Construction",
    "legacyPage": "https://allscopeconcrete.com.au/sydney-international-airport/",
    "status": "completed",
    "statusNote": null,
    "lead": {
      "assetId": "ASC-SYD-001",
      "label": null,
      "src": "/media/leads/PROJECT-05-SYDNEY-INTERNATIONAL-AIRPORT-01.webp",
      "width": 1181,
      "height": 787,
      "preferredCrop": "16:9 desktop / 4:5 mobile; protect main structure and a quiet text zone"
    },
    "gallery": [
      {
        "assetId": "OWN-SYD-01",
        "src": "/media/projects/sydney-international-airport/OWN-SYD-01.webp",
        "width": 2000,
        "height": 2667,
        "orientation": "portrait",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "The pump line, run through the live terminal during night works."
      },
      {
        "assetId": "OWN-SYD-02",
        "src": "/media/projects/sydney-international-airport/OWN-SYD-02.webp",
        "width": 2000,
        "height": 2667,
        "orientation": "portrait",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Trench reinforcement and substrate works inside the terminal."
      },
      {
        "assetId": "OJ4-SYD-01",
        "src": "/media/projects/sydney-international-airport/OJ4-SYD-01.webp",
        "width": 2000,
        "height": 2178,
        "orientation": "portrait",
        "tier": "B",
        "render": false,
        "contextOnly": true,
        "caption": "Project context: the completed T1 departures concourse."
      }
    ]
  },
  {
    "slug": "oran-park-hotel",
    "order": 6,
    "code": "OPH",
    "name": "Oran Park Hotel",
    "location": "Oran Park",
    "sector": "hospitality",
    "team": "Momento Hospitality / Versatile / Archebiosis",
    "legacyPage": "https://allscopeconcrete.com.au/oran-park-hotel/",
    "status": "completed",
    "statusNote": null,
    "lead": {
      "assetId": "OJ4-OPH-01",
      "label": null,
      "src": "/media/leads/OJ4-OPH-01.webp",
      "width": 2400,
      "height": 1800,
      "preferredCrop": "16:9 desktop / 4:5 mobile; protect main structure and a quiet text zone"
    },
    "gallery": [
      {
        "assetId": "OJ4-OPH-02",
        "src": "/media/projects/oran-park-hotel/OJ4-OPH-02.webp",
        "width": 2000,
        "height": 1300,
        "orientation": "landscape",
        "tier": "A",
        "render": false,
        "contextOnly": false,
        "caption": "The off-form concrete sign wall at the hotel entry."
      }
    ]
  },
  {
    "slug": "asha-westmead",
    "order": 7,
    "code": "ASH",
    "name": "Asha Westmead",
    "location": "Westmead",
    "sector": "multi-residential",
    "team": "Resico",
    "legacyPage": "https://allscopeconcrete.com.au/asha-westmead/",
    "status": "completed",
    "statusNote": null,
    "lead": {
      "assetId": "ASC-ASH-004",
      "label": null,
      "src": "/media/leads/PROJECT-07-ASHA-WESTMEAD-01.webp",
      "width": 1600,
      "height": 1068,
      "preferredCrop": "16:9 desktop / 4:5 mobile; protect main structure and a quiet text zone"
    },
    "gallery": [
      {
        "assetId": "ASC-ASH-005",
        "src": "/media/projects/asha-westmead/ASC-ASH-005.webp",
        "width": 1600,
        "height": 1068,
        "orientation": "landscape",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Asha-branded lobby and entry."
      },
      {
        "assetId": "ASC-ASH-006",
        "src": "/media/projects/asha-westmead/ASC-ASH-006.webp",
        "width": 1600,
        "height": 1068,
        "orientation": "landscape",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Internal landscaped courtyard."
      },
      {
        "assetId": "ASC-ASH-007",
        "src": "/media/projects/asha-westmead/ASC-ASH-007.webp",
        "width": 1600,
        "height": 1068,
        "orientation": "landscape",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Podium lawn and landscaped space."
      },
      {
        "assetId": "ASC-ASH-008",
        "src": "/media/projects/asha-westmead/ASC-ASH-008.webp",
        "width": 1600,
        "height": 1068,
        "orientation": "landscape",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Rooftop terrace and finished hardscape."
      },
      {
        "assetId": "ASC-ASH-010",
        "src": "/media/projects/asha-westmead/ASC-ASH-010.webp",
        "width": 1600,
        "height": 1068,
        "orientation": "landscape",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Façade, stair and material detail."
      },
      {
        "assetId": "OJ4-ASH-01",
        "src": "/media/projects/asha-westmead/OJ4-ASH-01.webp",
        "width": 2000,
        "height": 1335,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Rooftop hardscape and low planter walls on the finished rooftop."
      },
      {
        "assetId": "OJ4-ASH-02",
        "src": "/media/projects/asha-westmead/OJ4-ASH-02.webp",
        "width": 2000,
        "height": 1335,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": true,
        "caption": "Project context: the finished building from the street."
      }
    ]
  },
  {
    "slug": "one-the-waterfront",
    "order": 8,
    "code": "OTW",
    "name": "One The Waterfront",
    "location": "Wentworth Point",
    "sector": "multi-residential",
    "team": "Piety THP / Stanisic Architects",
    "legacyPage": "https://allscopeconcrete.com.au/one-the-waterfront/",
    "status": "completed",
    "statusNote": null,
    "lead": {
      "assetId": "ASC-OTW-003",
      "label": null,
      "src": "/media/leads/PROJECT-08-ONE-THE-WATERFRONT-01.webp",
      "width": 2133,
      "height": 1600,
      "preferredCrop": "16:9 desktop / 4:5 mobile; protect main structure and a quiet text zone"
    },
    "gallery": [
      {
        "assetId": "ASC-OTW-005",
        "src": "/media/projects/one-the-waterfront/ASC-OTW-005.webp",
        "width": 768,
        "height": 1024,
        "orientation": "portrait",
        "tier": "D",
        "render": false,
        "contextOnly": false,
        "caption": "Active wet-concrete placement over reinforcement."
      },
      {
        "assetId": "ASC-OTW-006",
        "src": "/media/projects/one-the-waterfront/ASC-OTW-006.webp",
        "width": 768,
        "height": 1024,
        "orientation": "portrait",
        "tier": "D",
        "render": false,
        "contextOnly": false,
        "caption": "Wide formwork, reinforcement and crane progress."
      },
      {
        "assetId": "ASC-OTW-007",
        "src": "/media/projects/one-the-waterfront/ASC-OTW-007.webp",
        "width": 768,
        "height": 1024,
        "orientation": "portrait",
        "tier": "D",
        "render": false,
        "contextOnly": false,
        "caption": "Formwork and reinforcement deck progress."
      },
      {
        "assetId": "ASC-OTW-009",
        "src": "/media/projects/one-the-waterfront/ASC-OTW-009.webp",
        "width": 3985,
        "height": 2907,
        "orientation": "landscape",
        "tier": "A",
        "render": false,
        "contextOnly": true,
        "caption": "Site aerial during crane erection."
      },
      {
        "assetId": "ASC-OTW-010",
        "src": "/media/projects/one-the-waterfront/ASC-OTW-010.webp",
        "width": 4533,
        "height": 2905,
        "orientation": "landscape",
        "tier": "A",
        "render": false,
        "contextOnly": true,
        "caption": "Tower crane on the One The Waterfront site."
      },
      {
        "assetId": "ASC-OTW-011",
        "src": "/media/projects/one-the-waterfront/ASC-OTW-011.webp",
        "width": 4952,
        "height": 3054,
        "orientation": "landscape",
        "tier": "A",
        "render": false,
        "contextOnly": true,
        "caption": "Multiple tower cranes across the development."
      },
      {
        "assetId": "OJ4-OTW-01",
        "src": "/media/projects/one-the-waterfront/OJ4-OTW-01.webp",
        "width": 2000,
        "height": 1333,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": true,
        "caption": "Project context: the completed development at Wentworth Point."
      },
      {
        "assetId": "OJ4-OTW-02",
        "src": "/media/projects/one-the-waterfront/OJ4-OTW-02.webp",
        "width": 2000,
        "height": 1225,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": true,
        "caption": "Project context: Stage 2 of the development from the air."
      }
    ]
  },
  {
    "slug": "one-the-waterfront-parkside",
    "order": 9,
    "code": "OTP",
    "name": "One The Waterfront — Parkside",
    "location": "Wentworth Point",
    "sector": "multi-residential",
    "team": "Piety THP / Stanisic Architects",
    "legacyPage": "https://allscopeconcrete.com.au/one-the-waterfront-parkside/",
    "status": "completed",
    "statusNote": null,
    "lead": {
      "assetId": "ASC-OTP-004",
      "label": null,
      "src": "/media/leads/PROJECT-09-ONE-THE-WATERFRONT-PARKSIDE-01.webp",
      "width": 2048,
      "height": 1365,
      "preferredCrop": "16:9 desktop / 4:5 mobile; protect main structure and a quiet text zone"
    },
    "gallery": [
      {
        "assetId": "ASC-OTP-006",
        "src": "/media/projects/one-the-waterfront-parkside/ASC-OTP-006.webp",
        "width": 1511,
        "height": 1397,
        "orientation": "square",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Completed exterior from Bay Park."
      },
      {
        "assetId": "ASC-OTP-005",
        "src": "/media/projects/one-the-waterfront-parkside/ASC-OTP-005.webp",
        "width": 2400,
        "height": 1600,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Completed Parkside pool and apartment setting."
      },
      {
        "assetId": "ASC-OTP-007",
        "src": "/media/projects/one-the-waterfront-parkside/ASC-OTP-007.webp",
        "width": 1600,
        "height": 1482,
        "orientation": "square",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Rooftop bridge and landscape."
      },
      {
        "assetId": "ASC-OTP-002",
        "src": "/media/projects/one-the-waterfront-parkside/ASC-OTP-002.webp",
        "width": 1020,
        "height": 680,
        "orientation": "landscape",
        "tier": "D",
        "render": false,
        "contextOnly": false,
        "caption": "Parkside completed landscaped courtyard."
      },
      {
        "assetId": "ASC-OTP-008",
        "src": "/media/projects/one-the-waterfront-parkside/ASC-OTP-008.webp",
        "width": 1067,
        "height": 1600,
        "orientation": "portrait",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Tower facade from Hill Road."
      },
      {
        "assetId": "ASC-OTP-009",
        "src": "/media/projects/one-the-waterfront-parkside/ASC-OTP-009.webp",
        "width": 1067,
        "height": 1600,
        "orientation": "portrait",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Landscaped Bennelong Parkway entry."
      },
      {
        "assetId": "ASC-OTP-003",
        "src": "/media/projects/one-the-waterfront-parkside/ASC-OTP-003.webp",
        "width": 680,
        "height": 1021,
        "orientation": "portrait",
        "tier": "D",
        "render": false,
        "contextOnly": false,
        "caption": "Parkside tower street exterior."
      }
    ]
  },
  {
    "slug": "view-rockdale",
    "order": 10,
    "code": "VRK",
    "name": "VIEW Rockdale",
    "location": "Rockdale",
    "sector": "multi-residential",
    "team": "Piety THP / Fuse Architects",
    "legacyPage": "https://allscopeconcrete.com.au/view-rockdale/",
    "status": "completed",
    "statusNote": null,
    "lead": {
      "assetId": "ASC-VRK-007",
      "label": null,
      "src": "/media/leads/PROJECT-10-VIEW-ROCKDALE-01.webp",
      "width": 1568,
      "height": 980,
      "preferredCrop": "16:9 desktop / 4:5 mobile; protect main structure and a quiet text zone"
    },
    "gallery": [
      {
        "assetId": "ASC-VRK-004",
        "src": "/media/projects/view-rockdale/ASC-VRK-004.webp",
        "width": 720,
        "height": 1280,
        "orientation": "portrait",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Golden curved façade under construction."
      },
      {
        "assetId": "ASC-VRK-008",
        "src": "/media/projects/view-rockdale/ASC-VRK-008.webp",
        "width": 1330,
        "height": 998,
        "orientation": "landscape",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Daytime three-quarter street exterior."
      },
      {
        "assetId": "ASC-VRK-005",
        "src": "/media/projects/view-rockdale/ASC-VRK-005.webp",
        "width": 960,
        "height": 1280,
        "orientation": "portrait",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Curved façade and scaffold progress."
      },
      {
        "assetId": "ASC-VRK-012",
        "src": "/media/projects/view-rockdale/ASC-VRK-012.webp",
        "width": 1330,
        "height": 997,
        "orientation": "landscape",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Symmetrical white breezeway and soffit."
      },
      {
        "assetId": "ASC-VRK-006",
        "src": "/media/projects/view-rockdale/ASC-VRK-006.webp",
        "width": 960,
        "height": 1280,
        "orientation": "portrait",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "White façade and bronze fin detail."
      },
      {
        "assetId": "ASC-VRK-009",
        "src": "/media/projects/view-rockdale/ASC-VRK-009.webp",
        "width": 876,
        "height": 1166,
        "orientation": "portrait",
        "tier": "D",
        "render": false,
        "contextOnly": false,
        "caption": "Golden internal breezeway with people."
      },
      {
        "assetId": "ASC-VRK-010",
        "src": "/media/projects/view-rockdale/ASC-VRK-010.webp",
        "width": 875,
        "height": 1166,
        "orientation": "portrait",
        "tier": "D",
        "render": false,
        "contextOnly": false,
        "caption": "Bronze fin and city-view detail."
      },
      {
        "assetId": "ASC-VRK-011",
        "src": "/media/projects/view-rockdale/ASC-VRK-011.webp",
        "width": 875,
        "height": 1166,
        "orientation": "portrait",
        "tier": "D",
        "render": false,
        "contextOnly": false,
        "caption": "Second bronze-fin detail."
      },
      {
        "assetId": "OJ4-VRK-01",
        "src": "/media/projects/view-rockdale/OJ4-VRK-01.webp",
        "width": 2000,
        "height": 1500,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Courtyard and hardscape detail from above at VIEW."
      },
      {
        "assetId": "OJ4-VRK-02",
        "src": "/media/projects/view-rockdale/OJ4-VRK-02.webp",
        "width": 2000,
        "height": 1500,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": true,
        "caption": "Project context: the completed building in Rockdale."
      }
    ]
  },
  {
    "slug": "bay-pavilions-lane-cove",
    "order": 11,
    "code": "BPL",
    "name": "Bay Pavilions",
    "location": "Lane Cove",
    "sector": "multi-residential",
    "team": "Piety THP / Alliance Project Group / Marchese Partners",
    "legacyPage": "https://allscopeconcrete.com.au/bay-pavilion-lane-cove/",
    "status": "completed",
    "statusNote": null,
    "lead": {
      "assetId": "ASC-BPL-008",
      "label": null,
      "src": "/media/leads/PROJECT-11-BAY-PAVILIONS-LANE-COVE-01.webp",
      "width": 1920,
      "height": 1280,
      "preferredCrop": "16:9 desktop / 4:5 mobile; protect main structure and a quiet text zone"
    },
    "gallery": [
      {
        "assetId": "ASC-BPL-001",
        "src": "/media/projects/bay-pavilions-lane-cove/ASC-BPL-001.webp",
        "width": 2048,
        "height": 1365,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Completed Bay Pavilions exterior."
      },
      {
        "assetId": "ASC-BPL-002",
        "src": "/media/projects/bay-pavilions-lane-cove/ASC-BPL-002.webp",
        "width": 1365,
        "height": 2048,
        "orientation": "portrait",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Vertical Bay Pavilions façade and sky."
      },
      {
        "assetId": "ASC-BPL-003",
        "src": "/media/projects/bay-pavilions-lane-cove/ASC-BPL-003.webp",
        "width": 2048,
        "height": 1365,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Completed Bay Pavilions exterior."
      },
      {
        "assetId": "ASC-BPL-007",
        "src": "/media/projects/bay-pavilions-lane-cove/ASC-BPL-007.webp",
        "width": 1920,
        "height": 2880,
        "orientation": "portrait",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Completed building and approach."
      },
      {
        "assetId": "ASC-BPL-004",
        "src": "/media/projects/bay-pavilions-lane-cove/ASC-BPL-004.webp",
        "width": 2048,
        "height": 1365,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Completed Bay Pavilions exterior."
      },
      {
        "assetId": "ASC-BPL-009",
        "src": "/media/projects/bay-pavilions-lane-cove/ASC-BPL-009.webp",
        "width": 1920,
        "height": 2880,
        "orientation": "portrait",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Bay Pavilions entry sign and façade."
      },
      {
        "assetId": "ASC-BPL-005",
        "src": "/media/projects/bay-pavilions-lane-cove/ASC-BPL-005.webp",
        "width": 2048,
        "height": 1365,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Completed Bay Pavilions exterior."
      },
      {
        "assetId": "ASC-BPL-010",
        "src": "/media/projects/bay-pavilions-lane-cove/ASC-BPL-010.webp",
        "width": 1920,
        "height": 2880,
        "orientation": "portrait",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Low-angle façade and balcony detail."
      },
      {
        "assetId": "ASC-BPL-006",
        "src": "/media/projects/bay-pavilions-lane-cove/ASC-BPL-006.webp",
        "width": 2048,
        "height": 1365,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Completed Bay Pavilions exterior."
      },
      {
        "assetId": "OJ4-BPL-01",
        "src": "/media/projects/bay-pavilions-lane-cove/OJ4-BPL-01.webp",
        "width": 2000,
        "height": 3000,
        "orientation": "portrait",
        "tier": "B",
        "render": false,
        "contextOnly": true,
        "caption": "Project context: the project sign wall at the entry."
      }
    ]
  },
  {
    "slug": "twenty95-manly",
    "order": 12,
    "code": "T95",
    "name": "Twenty95",
    "location": "Manly",
    "sector": "mixed-use",
    "team": "Grocon / Construction Profile / CHROFI",
    "legacyPage": "https://allscopeconcrete.com.au/one-the-waterfront-parkside-copy/",
    "status": "completed",
    "statusNote": null,
    "lead": {
      "assetId": "OJ4-T95-01",
      "label": "Project context",
      "src": "/media/leads/OJ4-T95-01.webp",
      "width": 2400,
      "height": 1600,
      "preferredCrop": "16:9 desktop / 4:5 mobile; protect main structure and a quiet text zone"
    },
    "gallery": [
      {
        "assetId": "ASC-T95-005",
        "src": "/media/projects/twenty95-manly/ASC-T95-005.webp",
        "width": 800,
        "height": 1200,
        "orientation": "portrait",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Sydney Road façade and streetscape."
      },
      {
        "assetId": "ASC-T95-006",
        "src": "/media/projects/twenty95-manly/ASC-T95-006.webp",
        "width": 800,
        "height": 1200,
        "orientation": "portrait",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Completed building along side street."
      },
      {
        "assetId": "ASC-T95-007",
        "src": "/media/projects/twenty95-manly/ASC-T95-007.webp",
        "width": 800,
        "height": 1200,
        "orientation": "portrait",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Long urban approach view."
      },
      {
        "assetId": "ASC-T95-009",
        "src": "/media/projects/twenty95-manly/ASC-T95-009.webp",
        "width": 800,
        "height": 1200,
        "orientation": "portrait",
        "tier": "C",
        "render": false,
        "contextOnly": false,
        "caption": "Completed building framed by heritage context."
      }
    ]
  },
  {
    "slug": "oran-park-public-school",
    "order": 13,
    "code": "OPS",
    "name": "Oran Park Public School",
    "location": "Oran Park",
    "sector": "education",
    "team": "Stage and head-contractor details not recorded in the current source pack",
    "legacyPage": "https://www.instagram.com/allscope_concrete/",
    "status": "completed",
    "statusNote": null,
    "lead": {
      "assetId": "OJ4-OPS-01",
      "label": null,
      "src": "/media/leads/OJ4-OPS-01.webp",
      "width": 2400,
      "height": 1543,
      "preferredCrop": "16:9 desktop / 4:5 mobile; protect main structure and a quiet text zone"
    },
    "gallery": [
      {
        "assetId": "ASC-OPS-001",
        "src": "/media/projects/oran-park-public-school/ASC-OPS-001.webp",
        "width": 2400,
        "height": 1543,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Completed Oran Park Public School exterior."
      },
      {
        "assetId": "OJ4-OPS-02",
        "src": "/media/projects/oran-park-public-school/OJ4-OPS-02.webp",
        "width": 2000,
        "height": 1286,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "The concrete amphitheatre and piazza at dusk."
      },
      {
        "assetId": "OWN-OPS-01",
        "src": "/media/projects/oran-park-public-school/OWN-OPS-01.webp",
        "width": 2000,
        "height": 2667,
        "orientation": "portrait",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Fresh path panels, swirl and broom finishes still between the forms."
      },
      {
        "assetId": "OWN-OPS-02",
        "src": "/media/projects/oran-park-public-school/OWN-OPS-02.webp",
        "width": 2000,
        "height": 2667,
        "orientation": "portrait",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Mesh down and the pump line in ahead of an external slab pour."
      },
      {
        "assetId": "OWN-OPS-03",
        "src": "/media/projects/oran-park-public-school/OWN-OPS-03.webp",
        "width": 2000,
        "height": 2667,
        "orientation": "portrait",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Edge reinforcement and conduits set out along the wall line."
      },
      {
        "assetId": "OWN-OPS-04",
        "src": "/media/projects/oran-park-public-school/OWN-OPS-04.webp",
        "width": 2000,
        "height": 2667,
        "orientation": "portrait",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Exposed-aggregate finish up close."
      },
      {
        "assetId": "OWN-OPS-05",
        "src": "/media/projects/oran-park-public-school/OWN-OPS-05.webp",
        "width": 2000,
        "height": 1500,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Placing and finishing a slab across the campus."
      },
      {
        "assetId": "OWN-OPS-06",
        "src": "/media/projects/oran-park-public-school/OWN-OPS-06.webp",
        "width": 2000,
        "height": 1500,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Reinforcement and formwork ahead of a deck pour."
      }
    ]
  },
  {
    "slug": "bp-prestons",
    "order": 14,
    "code": "BPP",
    "name": "BP Prestons Service Station & Truck Stop",
    "location": "Prestons",
    "sector": "retail-fuel",
    "team": "Builder/developer/package details not recorded in the current source pack",
    "legacyPage": "https://www.thebenzinagroup.com/copy-of-west-gosford-development",
    "status": "completed",
    "statusNote": null,
    "lead": {
      "assetId": "ASC-BPP-001",
      "label": null,
      "src": "/media/leads/PROJECT-14-BP-PRESTONS-01.webp",
      "width": 1920,
      "height": 1280,
      "preferredCrop": "16:9 desktop / 4:5 mobile; protect main structure and a quiet text zone"
    },
    "gallery": [
      {
        "assetId": "OJ4-BPP-01",
        "src": "/media/projects/bp-prestons/OJ4-BPP-01.webp",
        "width": 2000,
        "height": 1333,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "The truck refuelling slab and forecourt under the canopy."
      },
      {
        "assetId": "OJ4-BPP-02",
        "src": "/media/projects/bp-prestons/OJ4-BPP-02.webp",
        "width": 2000,
        "height": 1333,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Finished driveway and forecourt concrete across the site."
      }
    ]
  },
  {
    "slug": "el-jannah-prestons",
    "order": 15,
    "code": "EJP",
    "name": "El Jannah Prestons",
    "location": "Prestons",
    "sector": "hospitality",
    "team": "Builder/developer/package details not recorded in the current source pack",
    "legacyPage": "https://eljannah.com.au/locations/nsw/prestons/",
    "status": "completed",
    "statusNote": null,
    "lead": {
      "assetId": "ASC-EJP-001",
      "label": null,
      "src": "/media/leads/PROJECT-15-EL-JANNAH-PRESTONS-01.webp",
      "width": 900,
      "height": 600,
      "preferredCrop": "16:9 desktop / 4:5 mobile; protect main structure and a quiet text zone"
    },
    "gallery": [
      {
        "assetId": "OJ4-EJP-02",
        "src": "/media/projects/el-jannah-prestons/OJ4-EJP-02.webp",
        "width": 2000,
        "height": 1333,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "Forecourt paths and kerbs around the restaurant."
      },
      {
        "assetId": "OJ4-EJP-01",
        "src": "/media/projects/el-jannah-prestons/OJ4-EJP-01.webp",
        "width": 2000,
        "height": 1333,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": true,
        "caption": "Project context: the completed restaurant entry at Prestons."
      }
    ]
  },
  {
    "slug": "bp-oberon",
    "order": 16,
    "code": "BPO",
    "name": "BP Oberon",
    "location": "Oberon",
    "sector": "retail-fuel",
    "team": "Builder/developer/package details not recorded in the current source pack",
    "legacyPage": "https://map.bp.com/en-US/AU/gas-station/oberon/bp-oberon/8621",
    "status": "completed",
    "statusNote": null,
    "lead": {
      "assetId": "ASC-BPO-001",
      "label": null,
      "src": "/media/leads/PROJECT-16-BP-OBERON-01.webp",
      "width": 1200,
      "height": 630,
      "preferredCrop": "16:9 desktop / 4:5 mobile; protect main structure and a quiet text zone"
    },
    "gallery": [
      {
        "assetId": "OJ4-BPO-01",
        "src": "/media/projects/bp-oberon/OJ4-BPO-01.webp",
        "width": 2000,
        "height": 1746,
        "orientation": "landscape",
        "tier": "B",
        "render": false,
        "contextOnly": false,
        "caption": "The entry and concrete forecourt at BP Oberon."
      }
    ]
  }
];

export const capabilityImages: CapabilityImage[] = [
  {
    "assetId": "ASC-CAP-001",
    "src": "/media/capability/ASC-CAP-001.webp",
    "width": 1206,
    "height": 1510,
    "orientation": "portrait",
    "tier": "C",
    "caption": "Allscope's 3 July 2022 basement-blinding.",
    "purpose": "Generic blinding/process detail or mobile card only after the original export is recovered and project is identified"
  },
  {
    "assetId": "ASC-CAP-003",
    "src": "/media/capability/ASC-CAP-003.webp",
    "width": 1206,
    "height": 669,
    "orientation": "landscape",
    "tier": "C",
    "caption": "Ride-on power trowel on reflective finished slab.",
    "purpose": "Placement and finishing capability section; verify provenance and obtain the original/highest-resolution file"
  },
  {
    "assetId": "ASC-CAP-004",
    "src": "/media/capability/ASC-CAP-004.webp",
    "width": 840,
    "height": 630,
    "orientation": "landscape",
    "tier": "D",
    "caption": "Aerial multi-truck concrete pour.",
    "purpose": "Homepage/process sequence or capability overview after original aerial media and site permission are recovered"
  },
  {
    "assetId": "OWN-CAP-146",
    "src": "/media/capability/OWN-CAP-146.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "tier": "B",
    "caption": "Placing a suspended slab from the boom, seen from above.",
    "purpose": "Pumping and placement"
  },
  {
    "assetId": "OWN-CAP-149",
    "src": "/media/capability/OWN-CAP-149.webp",
    "width": 2000,
    "height": 2000,
    "orientation": "square",
    "tier": "B",
    "caption": "A wide raft pour under way, screeding behind the hose.",
    "purpose": "Pour supervision"
  },
  {
    "assetId": "OWN-CAP-152",
    "src": "/media/capability/OWN-CAP-152.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "tier": "B",
    "caption": "Mesh, membrane and starter bars checked on pour day.",
    "purpose": "Pre-pour readiness"
  },
  {
    "assetId": "OWN-CAP-166",
    "src": "/media/capability/OWN-CAP-166.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "tier": "B",
    "caption": "A freshly floated basement slab.",
    "purpose": "Finished slabs"
  },
  {
    "assetId": "OWN-CAP-169",
    "src": "/media/capability/OWN-CAP-169.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "tier": "B",
    "caption": "Machine finishing under way while the pour continues.",
    "purpose": "Finishing"
  },
  {
    "assetId": "OWN-CAP-197",
    "src": "/media/capability/OWN-CAP-197.webp",
    "width": 2000,
    "height": 2667,
    "orientation": "portrait",
    "tier": "B",
    "caption": "A finished charcoal driveway with a contrast border band.",
    "purpose": "External works"
  },
  {
    "assetId": "OWN-CAP-215",
    "src": "/media/capability/OWN-CAP-215.webp",
    "width": 2000,
    "height": 816,
    "orientation": "landscape",
    "tier": "B",
    "caption": "A fresh deck poured and finished, starter bars ready for the next lift.",
    "purpose": "Wide band"
  }
];
